# This is a basic workflow to help you get started with Actions

name: AWS Marketplace AMI Creation Workflow

# Controls when the action will run. 
on:
  workflow_dispatch:
    inputs:
      name:
        description: "AMI Name"
        required: true
      region:
        description: "AWS Region"
        required: true
        default: "us-east-1" 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  aws-ami-release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Setup AWS CLI
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set default.region $AWS_REGION
          aws configure get region
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_CM_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_CM_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ github.event.inputs.region }}
      - name: Echo $GITHUB_WORKSPACE
        run: echo "$GITHUB_WORKSPACE"
      # Runs a set of commands using the runners shell
      - name: Create AMI
        env:
          NAME: ${{github.event.inputs.name}}
          REGION: ${{github.event.inputs.region}}
        timeout-minutes: 15
        run: |
          bash ${GITHUB_WORKSPACE}/aws/couchbase-ami-creation/create.sh \
                                                                -r "$REGION" \
                                                                -n "$NAME" 
      - name: Upload AMI details
        uses: actions/upload-artifact@v2
        with:
          name: ${{github.event.inputs.name}}.json
          path: build/aws/couchbase-ami-creation/${{github.event.inputs.name}}.json
          retention-days: 14                                                                
                                                               